force-app/main/default/objects/Book_Copy__c/Book_Copy__c.object-meta.xml
<CustomObject>
    <label>Book Copy</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Call Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Copies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Copy__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The branch this copy currently resides in</description>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Book Copies</relationshipLabel>
    <relationshipName>Book_Copies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This field only applies to Librarians.</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Librarian</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Librarians</relationshipLabel>
    <relationshipName>Librarians</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Librarian_User__c.field-meta.xml
<CustomField>
    <fullName>Librarian_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Librarian User</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>User must be a librarian.</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Librarian</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>LibrarianContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TaskCreator.cls
public with sharing class TaskCreator {
    
    public static void createRemovalTask(List<Book_Copy__c> bcs){

        List<Branch__c> branches = [select id,name from branch__c];
        List<Task> tasks = new List<Task>();
        for(Branch__c branch: branches){
            String toRemove = 'Remove book copies with the following serial numbers from circulation:\n';
            for(Book_Copy__c bc: bcs){
                if(bc.branch__c == branch.id){
                    toRemove += bc.name+'\n';
                }
            }
            Id librarianContactId = [select id from contact where branch__c=:branch.id limit 1].id;
            Id librarianUserId = [select librarian_user__c from contact where id =: librarianContactId limit 1].librarian_user__c;
            tasks.add(new Task(Subject = 'Remove from Circulation', OwnerId = librarianUserId, Priority = 'Normal',
                ActivityDate = Date.today().addDays(7), Status = 'Not Started', Description = toRemove, WhatId = branch.id ));
        }
        insert tasks;

    }
        
}