force-app/main/default/objects/Book_Copy__c/Book_Copy__c.object-meta.xml
<CustomObject>
    <label>Book Copy</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Call Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Copies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Copy__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The branch this copy currently resides in</description>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Book Copies</relationshipLabel>
    <relationshipName>Book_Copies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book_Copy__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Book_Copy__c/fields/Flagged_for_Removal__c.field-meta.xml
<CustomField>
    <fullName>Flagged_for_Removal__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This box is checked if a book copy is flagged for removal from circulation. Books removed from circulation can be thrown away, donated, or sold at the next book sale.</inlineHelpText>
    <label>Flagged for Removal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BookFlagger.cls
global class BookFlagger implements Database.Batchable<sObject>, Schedulable {

    global Database.QueryLocator start(Database.BatchableContext BC){

        String query = 'SELECT id,name,flagged_for_removal__c,branch__c from book_copy__c WHERE condition__c LIKE \'damaged\' ORDER BY name';
        return Database.getQueryLocator(query);
    }
  

   global void execute(Database.BatchableContext BC, List<Book_Copy__c> bcs){

        for(Book_Copy__c bcopy: bcs){
            bcopy.flagged_for_removal__c = true;
        }
        update bcs;
        TaskCreator.createRemovalTask(bcs);

    }
  
   global void finish(Database.BatchableContext BC){

    Id librarianProfileId = [select id from profile where name like 'Librarian'].id;
    List<User> librarianUsers = [select email from user where profileid =: librarianProfileId];
    List<String> toAddresses = new List<String>();
    for(User u: librarianUsers){
        toAddresses.add(u.email);
    }

    
    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
    mail.setToAddresses(toAddresses);
    mail.setSaveAsActivity(false);
    EmailTemplate librarianTemplate = [SELECT id,subject,htmlValue FROM EmailTemplate WHERE name LIKE 'Librarian Email Template'];
    mail.setTemplateId(librarianTemplate.id);
    mail.setSubject(librarianTemplate.subject);
    mail.setHtmlBody(librarianTemplate.htmlValue);
    Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); 
   }

   global void execute(SchedulableContext sc) {
        BookFlagger bf = new BookFlagger ();
        database.executebatch(bf);
    }
}