force-app/main/default/objects/Librarian__c/Librarian__c.object-meta.xml
<CustomObject>
    <description>An object for attaching lookup fields to a Librarian user.</description>
    <label>Librarian</label>
    <nameField>
        <label>Librarian Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Librarians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Librarian__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Librarian</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Librarians</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LibrarianRecordUpdaterQueueable.cls
public with sharing class LibrarianRecordUpdaterQueueable implements Queueable {
    private List<Id> users;

    public LibrarianRecordUpdaterQueueable(List<Id> users) {
        this.users = users;
    }

    public void execute(QueueableContext context) {
        //Trigger a workflow rule that updates a librarian's name
        Update [SELECT Id FROM Librarian__c WHERE User__c IN :users FOR UPDATE];
    }
}