force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Copy__c/Book_Copy__c.object-meta.xml
<CustomObject>
    <label>Book Copy</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Call Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Copies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Copy__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Book Copies</relationshipLabel>
    <relationshipName>Book_Copies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Book_Copy__c/fields/Borrower__c.field-meta.xml
<CustomField>
    <fullName>Borrower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Borrower</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Book Copies</relationshipLabel>
    <relationshipName>Book_Copies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book_Copy__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The branch this copy currently resides in</description>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Book Copies</relationshipLabel>
    <relationshipName>Book_Copies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book_Copy__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This field only applies to Librarians.</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Librarian</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Librarians</relationshipLabel>
    <relationshipName>Librarians</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <inlineHelpText>What is the number on the Borrower&apos;s library card?</inlineHelpText>
    <label>Card Number</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Borrower.recordType-meta.xml
<RecordType>
    <fullName>Borrower</fullName>
    <active>true</active>
    <label>Borrower</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Librarian.recordType-meta.xml
<RecordType>
    <fullName>Librarian</fullName>
    <active>false</active>
    <label>Librarian</label>
</RecordType>

force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>{MM}-{DD}-{YYYY}-{00000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Book_Copy__c.field-meta.xml
<CustomField>
    <fullName>Book_Copy__c</fullName>
    <inlineHelpText>What was loaned?</inlineHelpText>
    <label>Book Copy</label>
    <referenceTo>Book_Copy__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Borrower__c.field-meta.xml
<CustomField>
    <fullName>Borrower__c</fullName>
    <inlineHelpText>Who was this loaned to?</inlineHelpText>
    <label>Borrower</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Checkout__c.field-meta.xml
<CustomField>
    <fullName>Checkout__c</fullName>
    <inlineHelpText>When was this book checked out?</inlineHelpText>
    <label>Checkout</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Due__c.field-meta.xml
<CustomField>
    <fullName>Due__c</fullName>
    <inlineHelpText>When is this due back?</inlineHelpText>
    <label>Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Returned__c.field-meta.xml
<CustomField>
    <fullName>Returned__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Has this been returned yet?</inlineHelpText>
    <label>Returned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BookControllerTests.cls
@isTest
public with sharing class BookControllerTests {
    @TestSetup
    static void makeData(){
        Branch__c branch = TestDataFactory.createBranch();
        Insert branch;

        User librarian = TestDataFactory.createLibrarian();
        Test.startTest();
        Insert librarian;
        Test.stopTest();
        TestDataFactory.setLibrarianBranch(librarian.Id, branch.Id);

        Book__c book = TestDataFactory.createBook();
        Insert book;

        Insert TestDataFactory.createBookCopy(book.Id, branch.Id);

        Insert TestDataFactory.createBorrower();
    }

    @isTest
    public static void checkoutBookTest() {
        User librarian = [SELECT Id FROM User WHERE Name='Test Test'];
        
        System.runAs(librarian) {
            Contact borrower = [SELECT Id,Name,Card_Number__c FROM Contact WHERE RecordType.Name='Borrower'];
            Book_Copy__c bookCopy = [SELECT Id,Name,Book__r.Name FROM Book_Copy__c];

            String result = BookController.checkoutBook(bookCopy.Name, borrower.Card_Number__c);
            System.assertEquals('Checked out copy of ' + bookCopy.Book__r.Name + ' to ' + borrower.Name, result);

            Loan__c loan = [SELECT Borrower__c,Checkout__c,Due__c FROM Loan__c WHERE Book_Copy__c=:bookCopy.Id];
            System.assertEquals(borrower.Id, loan.Borrower__c);
            System.assertEquals(Date.today(), loan.Checkout__c);
            System.assertEquals(Date.today().addDays(14), loan.Due__c);

            bookCopy = [SELECT Borrower__c,Branch__c,Condition__c FROM Book_Copy__c WHERE Id=:bookCopy.Id];
            System.assertEquals(borrower.Id, bookCopy.Borrower__c);
            System.assertEquals(null, bookCopy.Branch__c);
            System.assertEquals('Used', bookCopy.Condition__c);
        }
    }

    @isTest
    public static void checkoutBookInvalidBookErrorTest() {
        User librarian = [SELECT Id FROM User WHERE Name='Test Test'];
        
        System.runAs(librarian) {
            Contact borrower = [SELECT Card_Number__c FROM Contact WHERE RecordType.Name='Borrower'];

            Boolean gotError = false;
            try {
                BookController.checkoutBook('', borrower.Card_Number__c);
            } catch (InputException e) {
                gotError = true;
                System.assertEquals('Invalid Book Serial Number', e.getMessage());
            }

            System.assert(gotError);
        }
    }

    @isTest
    public static void checkoutBookInvalidBorrowerErrorTest() {
        User librarian = [SELECT Id FROM User WHERE Name='Test Test'];
        
        System.runAs(librarian) {
            Book_Copy__c bookCopy = [SELECT Name FROM Book_Copy__c];

            Boolean gotError = false;
            try {
                BookController.checkoutBook(bookCopy.Name, '');
            } catch (InputException e) {
                gotError = true;
                System.assertEquals('Invalid Card Number', e.getMessage());
            }

            System.assert(gotError);
        }
    }

    @isTest
    public static void checkoutBookCheckedOutErrorTest() {
        User librarian = [SELECT Id FROM User WHERE Name='Test Test'];
        
        System.runAs(librarian) {
            Contact borrower = [SELECT Card_Number__c FROM Contact WHERE RecordType.Name='Borrower'];
            Book_Copy__c bookCopy = [SELECT Name FROM Book_Copy__c];

            BookController.checkoutBook(bookCopy.Name, borrower.Card_Number__c);

            Boolean gotError = false;
            try {
                BookController.checkoutBook(bookCopy.Name, borrower.Card_Number__c);
            } catch (InputException e) {
                gotError = true;
                System.assertEquals('Book is already checked out', e.getMessage());
            }

            System.assert(gotError);
        }
    }

    @isTest
    public static void returnBookTest(){
        User librarian = [SELECT Id FROM User WHERE Name='Test Test'];
        
        System.runAs(librarian) {
            Contact borrower = [SELECT Id,Name,Card_Number__c FROM Contact WHERE RecordType.Name='Borrower'];
            Book_Copy__c bookCopy = [SELECT Id,Name FROM Book_Copy__c LIMIT 1];

            String checkedOut = BookController.checkoutBook(bookCopy.Name, borrower.Card_Number__c);

            String result = BookController.returnBook(bookCopy.Name, true);
            System.assertEquals('Return successful.',result);

            Loan__c loan = [SELECT Returned__c FROM Loan__c WHERE Book_Copy__c=:bookCopy.Id];
            System.assertEquals(true, loan.Returned__c);

            bookCopy = [SELECT Borrower__c,Branch__c,Condition__c FROM Book_Copy__c WHERE Id=:bookCopy.Id];
            System.assertEquals(null, bookCopy.Borrower__c);
            System.assertEquals(BranchHelper.getBranch().id, bookCopy.Branch__c);
            System.assertEquals('Damaged',bookCopy.Condition__c);
        }
    }
}