force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Copy__c/Book_Copy__c.object-meta.xml
<CustomObject>
    <label>Book Copy</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Call Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Copies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Copy__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Book Copies</relationshipLabel>
    <relationshipName>Book_Copies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Book_Copy__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The branch this copy currently resides in</description>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Book Copies</relationshipLabel>
    <relationshipName>Book_Copies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book_Copy__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This field only applies to Librarians.</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Librarian</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Librarians</relationshipLabel>
    <relationshipName>Librarians</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <inlineHelpText>What is the number on the Borrower&apos;s library card?</inlineHelpText>
    <label>Card Number</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Librarian_User__c.field-meta.xml
<CustomField>
    <fullName>Librarian_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Librarian User</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>User must be a librarian.</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Librarian</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>LibrarianContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Borrower.recordType-meta.xml
<RecordType>
    <fullName>Borrower</fullName>
    <active>true</active>
    <label>Borrower</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Librarian.recordType-meta.xml
<RecordType>
    <fullName>Librarian</fullName>
    <active>false</active>
    <label>Librarian</label>
</RecordType>

force-app/main/default/classes/TestDataFactory.cls
public inherited sharing class TestDataFactory {
    public static User createLibrarian() {
        Profile librarianProfile = [SELECT Id FROM Profile WHERE Name='Librarian'];
        return new User(
            ProfileId = librarianProfile.Id,
            FirstName = 'Test',
            LastName = 'Test',
            Alias = 'test',
            Email = 'test@test.com',
            Username = 'test@testasdf.com',
            TimeZoneSidKey = 'GMT',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LocaleSidKey = 'en_US'
        );
    }

    public static Book__c createBook() {
        return new Book__c(
            Name = 'Test'
        );
    }

    public static Book_Copy__c createBookCopy(Id bookId, Id branchId) {
        return new Book_Copy__c(
            Condition__c = 'New',
            Book__c = bookId,
            Branch__c = branchId
        );
    }

    public static Branch__c createBranch() {
        return new Branch__c(
            Name = 'Test',
            Location__Latitude__s = 0,
            Location__Longitude__s = 0
        );
    }

    private static Integer borrowerNumber = 0;

    public static Contact createBorrower() {
        RecordType borrowerRecordType = [SELECT Id FROM RecordType WHERE SobjectType='Contact' AND Name='Borrower'];
        return new Contact(
            RecordTypeId = borrowerRecordType.Id,
            FirstName = 'Test',
            LastName = 'Test',
            Card_Number__c = String.valueOf(borrowerNumber++)
        );
    }

    public static void setLibrarianBranch(Id librarianUserId, Id branchId) {
        Contact librarianContact = [Select Id, Branch__c FROM Contact WHERE Librarian_User__c=:librarianUserId];
        librarianContact.Branch__c = branchId;
        Update librarianContact;
    }
}