force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>{MM}-{DD}-{YYYY}-{00000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Borrower__c.field-meta.xml
<CustomField>
    <fullName>Borrower__c</fullName>
    <inlineHelpText>Who was this loaned to?</inlineHelpText>
    <label>Borrower</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Overdue__c.field-meta.xml
<CustomField>
    <fullName>Overdue__c</fullName>
    <formula>IF( (Returned__c == FALSE &amp;&amp; (TODAY()- Due__c &gt; 0)),TRUE,FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If the book has not been returned yet and it is past the loan&apos;s due date, then the loan is overdue.</inlineHelpText>
    <label>Overdue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OverdueReminder.cls
global class OverdueReminder implements Database.Batchable<sObject>, Schedulable {
    
    global Database.QueryLocator start(Database.BatchableContext BC){

        List<AggregateResult> overdueLoans = [SELECT Borrower__c FROM Loan__c WHERE overdue__c = TRUE GROUP BY Borrower__c];
        List<id> overdueBorrowerIds = new List<id>();

        for(AggregateResult agg: overdueLoans){
            overdueBorrowerIds.add((id)agg.get('Borrower__c'));
        }

        String query = 'SELECT id,email FROM Contact WHERE id IN :overdueBorrowerIds';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Contact> overdueBorrowers){

        for(Contact c: overdueBorrowers){
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            List<String> toAddresses = new List<String>();
            toAddresses.add(c.email);
            mail.setToAddresses(toAddresses);
            mail.setSaveAsActivity(false);
            EmailTemplate overdueTemplate = [SELECT id,subject,htmlValue FROM EmailTemplate WHERE name LIKE 'Overdue Notice'];
            mail.setTemplateId(overdueTemplate.id);
            mail.setTargetObjectId(c.id);
            mail.setWhatId(c.id);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
    }

    global void finish(Database.BatchableContext BC){}

    global void execute(SchedulableContext sc) {
        OverdueReminder reminder = new OverdueReminder ();
        database.executebatch(reminder);
    }


}