force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This field only applies to Librarians.</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Librarian</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Librarians</relationshipLabel>
    <relationshipName>Librarians</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Librarian_User__c.field-meta.xml
<CustomField>
    <fullName>Librarian_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Librarian User</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>User must be a librarian.</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Librarian</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>LibrarianContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Librarian.recordType-meta.xml
<RecordType>
    <fullName>Librarian</fullName>
    <active>false</active>
    <label>Librarian</label>
</RecordType>

force-app/main/default/classes/LibrarianTests.cls
@isTest
public inherited sharing class LibrarianTests {
    @TestSetup
    static void makeData(){
        test.startTest();
        Insert TestDataFactory.createLibrarian();
        test.stopTest();
        Insert TestDataFactory.createBranch();
    }

    @isTest
    public static void librarianContactTest() {
        RecordType librarianRecordType = [SELECT Id FROM RecordType WHERE SobjectType='Contact' AND Name='Librarian'];
        Profile librarianProfile = [SELECT Id FROM Profile WHERE Name='Librarian'];

        User libUser = [SELECT Id,Name,Email FROM User WHERE ProfileId=:librarianProfile.Id AND Name='Test Test' LIMIT 1];
        Contact libContact = [SELECT Name,Email FROM Contact WHERE RecordTypeId=:librarianRecordType.Id AND Librarian_User__c=:libUser.Id];

        System.assertEquals(libUser.Name, libContact.Name);
        System.assertEquals(libUser.Email, libContact.Email);
    }

    @isTest
    public static void createLibrarianTasksTest() {
        RecordType librarianRecordType = [SELECT Id FROM RecordType WHERE SobjectType='Contact' and Name='Librarian'];
        Contact libContact = [SELECT Id FROM Contact WHERE RecordTypeId=:librarianRecordType.Id];

        Task libTask = [SELECT Subject,Status,Priority FROM Task WHERE WhoId=:libContact.Id];
        
        System.assertEquals('Assign Librarian to Branch', libTask.Subject);
        System.assertEquals('Not Started', libTask.Status);
        System.assertEquals('High', libTask.Priority);
    }

    @isTest
    public static void updateLibrarianTasksTest() {
        RecordType librarianRecordType = [SELECT Id FROM RecordType WHERE SobjectType='Contact' and Name='Librarian'];
        Contact libContact = [SELECT Id,Branch__c FROM Contact WHERE RecordTypeId=:librarianRecordType.Id];
        Branch__c branch = [SELECT Id FROM Branch__c LIMIT 1];

        libContact.Branch__c = branch.Id;

        Update libContact;

        Task libTask = [SELECT Status FROM Task WHERE WhoId=:libContact.Id];
        System.assertEquals('Completed', libTask.Status);
    }
}